language: python
sudo: false
cache: pip

python:
  # For branches <= 10.0, put `- "2.7.13"`
  - "2.7.13"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

stages:
  - linting
  - test

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    # Set this variable to some version existing as linux-generic build on
    # https://github.com/wkhtmltopdf/wkhtmltopdf/releases
    # if you need to install wkhtmltopdf
    # - WKHTMLTOPDF_VERSION="0.12.5"
    # Set the above to install a `wkhtmltopdf` version that is not the one provided
    # by the `pov-wkhtmltopdf` repo.

jobs:
  include:
    - stage: linting
      env:
        - LINT_CHECK="1"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="1"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
